from __future__ import annotations
import json
# import uuid
import re
import os
import subprocess
# import shutil
# from pathlib import Path
# from typing import Dict, List, Tuple, Any
# import gradio as gr
# import copy
# import random
# from datetime import datetime


# from run_helpers import (
#     _get_project_paths,
#     _get_sequence_paths,
#     _launch_detached_batch_script,
#     cancel_batch_script
# )

# SCRIPT_DIRECTORY = os.path.join(os.path.dirname(__file__), "scripts")

JOYCAPTION_PYTHON = r"D:\joycaption\joycaption-venv\Scripts\python.exe"
# JOYCAPTION_QC_SCRIPT = os.path.join(os.path.dirname(__file__), "scripts", "run_qc.py")
JOYCAPTION_QC_SCRIPT = os.path.join(os.path.dirname(__file__), "scripts", "qc", "run_qc.py")


import re

def clean_description_for_qc(description: str) -> str:
    """Remove LoRA triggers and technical tags from description."""
    # Cut everything from __lora: onwards
    match = re.search(r'__lora:', description, re.IGNORECASE)
    if match:
        description = description[:match.start()]
    
    # Cut from any __ pattern
    match = re.search(r'__\w', description)
    if match:
        description = description[:match.start()]
    
    # Remove words containing underscores
    words = description.split()
    words = [w for w in words if '_' not in w]
    description = ' '.join(words)
    
    # Clean up trailing commas and whitespace
    description = description.rstrip(', \t\n')
    
    return description

def read_image_snapshot(image_path: str) -> dict | None:
    """Read the embedded snapshot metadata from a PNG image."""
    try:
        from PIL import Image
        img = Image.open(image_path)
        snapshot_str = img.info.get("the_machine_snapshot")
        if snapshot_str:
            return json.loads(snapshot_str)
    except Exception as e:
        print(f"[QC] Failed to read snapshot from {image_path}: {e}")
    return None


def handle_pose_qc(image_path: str, description: str = None, pose: bool = False):
    """Score a generated pose image against its description using JoyCaption.
    
    If description is None or empty, attempts to read from embedded metadata.
    """
    print(f"[QC DEBUG] image_path: {image_path}")
    print(f"[QC DEBUG] description (from UI): {description}")
    
    output_lines = []
    
    if not image_path:
        yield "No image to score. Generate a pose first."
        return
    
    if not os.path.exists(image_path):
        yield f"Image not found: {image_path}"
        return
    
    snapshot = read_image_snapshot(image_path)
    if not snapshot:
        yield "No metadata found in image. Was it generated by this app?"
        return
    
    # description = snapshot.get("item_data", {}).get("layout", "")
    # setting = snapshot.get("sequence_context", {}).get("setting_prompt", "")

    # description = snapshot.get("item_data", {}).get("layout", "")
    # setting = ""
    # if not pose:
    #     seq_ctx = snapshot.get("sequence_context", {})
    #     setting = seq_ctx.get("setting_asset") or seq_ctx.get("setting_prompt", "")
    description = snapshot.get("item_data", {}).get("layout", "")
    description = clean_description_for_qc(description)
    setting = ""
    if not pose:
        seq_ctx = snapshot.get("sequence_context", {})
        setting = seq_ctx.get("setting_asset") or seq_ctx.get("setting_prompt", "")

    print(f"[QC DEBUG] description (from metadata): {description}")
    print(f"[QC DEBUG] setting (from metadata): {setting}")

    if not description:
        yield "No description found. Check image metadata or enter manually."
        return
        
    

    yield "\n".join(output_lines)

    output_lines.append(f"Image: {os.path.basename(image_path)}")
    output_lines.append(f"Prompt: {description}")
    if setting:
        output_lines.append(f"Setting: {setting[:60]}...")
    output_lines.append("Scoring...")
    yield "\n".join(output_lines)
    
    try:
        # result = subprocess.run(
        #     [
        #         JOYCAPTION_PYTHON,
        #         JOYCAPTION_QC_SCRIPT,
        #         "--image", str(image_path),
        #         "--description", description,
        #         "--json",
        #         "--max-new-tokens", "128"
        #     ],
        #     capture_output=True,
        #     text=True,
        #     timeout=120
        # )
        cmd = [
            JOYCAPTION_PYTHON,
            JOYCAPTION_QC_SCRIPT,
            "--image", str(image_path),
            "--json",
            "--max-new-tokens", "128"
        ]
        if pose:
            cmd.append("--pose")
        
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=120
        )
        # DEBUG: Uncomment to see raw script output
        # if result.stderr:
        #     output_lines.append(f"[stderr]: {result.stderr.strip()}")
        # output_lines.append(f"[stdout]: {result.stdout.strip()}")
        
        if result.returncode != 0:
            output_lines.append(f"Error: {result.stderr}")
            yield "\n".join(output_lines)
            return
        
        data = json.loads(result.stdout)
        score = data.get("score")
        reason = data.get("reason")
        
        max_score = 3 if pose else 5
        if score is None:
            output_lines.append(f"Could not parse score. Raw: {data.get('raw', 'N/A')}")
        elif reason:
            output_lines.append(f"Score: {score}/{max_score} — {reason}")
        else:
            output_lines.append(f"Score: {score}/{max_score}")
        
        yield "\n".join(output_lines)
            
    except subprocess.TimeoutExpired:
        output_lines.append("Timeout: scoring took too long")
        yield "\n".join(output_lines)
    except json.JSONDecodeError:
        output_lines.append(f"Failed to parse JSON: {result.stdout}")
        yield "\n".join(output_lines)
    except Exception as e:
        output_lines.append(f"Error: {e}")
        yield "\n".join(output_lines)


